[
    "../../../../../lib/run/javascriptcore.js",
    "../../../../main/js/jsasync.js",
    "../../../../../lib/test/json2.js",
    "../../../../../lib/test/jssert.js",
    "imports.js",
    "testData.js",
    "testutils.js"
].forEach(require);